### ISSUE TITLE
npm publish

### ISSUE THREAD

**Issue by ngoldman** [paulcpederson/site-shot#1]
https://www.npmjs.com/package/site-shot ain't nothin there yet m9

**Comment by paulcpederson** [comment]
I don't like to publish until a module is functioning. This is not there yet. As soon as I've complete mvp I will publish. It would I think be uncouth to publish this in a half completed state.

**Comment by ngoldman** [comment]
@paulcpederson I would agree -- but your readme has instructions on how to npm install, indicating that it's published. so maybe take that out until it is published?

**Comment by paulcpederson** [comment]
@ngoldman I added you as a collaborator 

[https://github.com/paulcpederson/site-shot/graphs/traffic](Checkout the traffic) - you and I (and me from my phone on a different IP) are the only people who have seen this page. Luckily I'm not a big deal in the node community...

**Comment by ngoldman** [comment]
yeah paul but it's about living the dream

**Comment by paulcpederson** [comment]
@ngoldman ++
