### ISSUE TITLE
decouple from server

### ISSUE THREAD

**Issue by ngoldman** [paulcpederson/site-shot#4]
What do you think about a future version of `site-shot` just pointing to any URL (local or remote) and pulling the static server component out? That way it could be focused on supporting FF, Chrome, Safari, etc., and not worry about directories or static site structures.

**Comment by ngoldman** [comment]
Thinking through this I guess having access to the directory is what allows `site-shot` to easily scan every page. Hmm.

**Comment by paulcpederson** [comment]
Yeah, otherwise you'd need to figure out a way to crawl the entire website...
